# -*- coding: utf-8 -*-
"""

    deployr

    by hgschmidt

    Copyright (c) 2012 apitrary

"""
# Message Queue name
#
#
GENAPI_DEPLOYMENT_QUEUE = 'genapi_deployment_queue'
GENAPI_DEPLOYMENT_CONFIRMATION_QUEUE = 'genapi_deployment_confirmation_queue'
LOADBALANCE_UPDATE_QUEUE = 'loadbalance_update_queue'
LOADBALANCE_UPDATE_CONFIRMATION_QUEUE = 'loadbalance_update_confirmation_queue'


# Routing keys
#
#
DEPLOY_ROUTING_KEY = GENAPI_DEPLOYMENT_QUEUE
DEPLOY_CONFIRMATION_ROUTING_KEY = GENAPI_DEPLOYMENT_CONFIRMATION_QUEUE
UNDEPLOY_ROUTING_KEY = GENAPI_DEPLOYMENT_QUEUE
UNDEPLOY_CONFIRMATION_ROUTING_KEY = GENAPI_DEPLOYMENT_CONFIRMATION_QUEUE
LOADBALANCE_UPDATE_ROUTING_KEY = LOADBALANCE_UPDATE_QUEUE
LOADBALANCE_UPDATE_CONFIRMATION_ROUTING_KEY = LOADBALANCE_UPDATE_CONFIRMATION_QUEUE